# Generated by Django 4.0.4 on 2022-06-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='items',
        ),
        migrations.AddField(
            model_name='carts',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.products'),
        ),
    ]
